/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.gui.myframes;

import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

import poo.negocios.ListarDisciplinas;
import poo.negocios.beans.Disciplina;

/**
 *
 * @author Thiago Gomes
 */
public class FrameListarDisciplinasNovo extends javax.swing.JInternalFrame {
	
	DefaultTableModel modelo = new DefaultTableModel();
	
    /**
     * Creates new form FrameListarDisciplinasNovo
     */
    public FrameListarDisciplinasNovo() {
        initComponents();
        this.definirTabela();
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCDepartamento = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCCurso = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Listar Disciplinas ");

        jCDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jCCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(jCCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(246, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void definirTabela(){
    	jTable1.setModel(modelo);
    	modelo.addColumn("Codigo");
    	modelo.addColumn("Nome");
    	modelo.addColumn("Carga Horaria");
    	jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
    	jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
    	jTable1.getColumnModel().getColumn(1).setPreferredWidth(30);
    	preencharTabela(modelo);
    }
    
    
    
    
    public void preencharTabela(DefaultTableModel modelo){
    	modelo.setNumRows(0);
    	ListarDisciplinas listar = ListarDisciplinas.getInstance();
//    	ArrayList<Disciplina> lista = listar.listarDisciplinasPorCurso(jCCurso.getName());
    	ArrayList<Disciplina> lista = listar.listarTodasAsDisciplinas();
    	for(Disciplina aux : lista){
    		modelo.addRow(new Object[]{aux.getCodigo(), aux.getNome(), aux.getCargaHoraria()});
    	}
    	
    	
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCCurso;
    private javax.swing.JComboBox<String> jCDepartamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
