/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.gui.myframes;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import poo.negocios.FachadaSistema;
import poo.negocios.beans.Disciplina;

/**
 *
 * @author Thiago Gomes
 */
public class FrameBuscaAvancada extends javax.swing.JInternalFrame {
    private FachadaSistema fachada;
    
    private class MeuModeloComMuitasLinhas extends AbstractTableModel {
        private List<Disciplina> linhas;
        private String[] colunas = {"Codigo", "Nome", "Carga Horaria", "Obrigatoria", "Optativa"};
        
        public MeuModeloComMuitasLinhas(){
            linhas = new ArrayList<Disciplina>();
        }
        
        public MeuModeloComMuitasLinhas(ArrayList<Disciplina> listaDisciplinas){
            
        }
        /**
         * A JTable chama esse método para saber quantas colunas ela possui
         */
        public int getColumnCount() {
            // minha JTable terá 3 colunas
            // poderia ter tantas quanto eu quisesse
            return colunas.length;
        }

        /**
         * A JTable chama esse método para saber qual é o nome da coluna informada
         */
        public String getColumnName(int col) {
            // o nome das colunas será "coluna 0", "coluna 1" e "coluna 2"
            // mas poderia ser algo mais óbvio como "Nome", "Idade" e "Gênero" por exemplo
            return colunas[col];
        }

        /**
         * A JTable chama esse método para saber quantos itens ela possui
         */
        public int getRowCount() {
            // minha JTable terá 10 mil linhas
            // mas poderia por exemplo retornar o tamanho da lista de objetos que quero renderizar
            return linhas.size();
        }

        /**
         * A JTable chama esse método para saber qual o valor que ela deve apresentar na célula informada
         */
        public Object getValueAt(int lin, int col) {
            // cada célula da minha JTable vai renderizar sua linha e sua coluna
            // mas poderia fazer o seguinte:
            // pegar o objeto na posição "lin" da lista
            // um switch da coluna e com isso
            // devolver o valor dos atributos "nome", "idade" e "genero"
            Disciplina p = linhas.get(lin);
            switch (col) {  
                case 0: // Primeira coluna é a Descrição.  
                    return p.getCodigo();  
                case 1: // Segunda coluna é o PreçoUnitario.  
                    return p.getNome();  
                case 2: // Terceira coluna é a Quantidade.  
                    return p.getCargaHoraria();  
                case 3: // Quarta coluna é o SubTotal.  
                    return p.getObrigatoria();  
                default:  
                    throw new IndexOutOfBoundsException("columnIndex out of bounds");  
            }
        }
    }
    /**
     * Creates new form FrameBuscaAvancada
     */
    public FrameBuscaAvancada() {
        initComponents();
        jTResultados = new JTable(new MeuModeloComMuitasLinhas());
//        jTResultados.
    }

    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTBusca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTResultados = new javax.swing.JTable();

        setClosable(true);
        setTitle("Busca Avançada (Disciplina)");

        jLabel1.setText("Palavra(s) chave(s):");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Carga Horaria", "Obrigatoria", "Optativa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTResultados.setColumnSelectionAllowed(true);
        jTResultados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTResultados);
        jTResultados.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTResultados.getColumnModel().getColumnCount() > 0) {
            jTResultados.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTResultados.getColumnModel().getColumn(0).setMaxWidth(90);
            jTResultados.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTResultados.getColumnModel().getColumn(2).setMaxWidth(90);
            jTResultados.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTResultados.getColumnModel().getColumn(3).setMaxWidth(90);
            jTResultados.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTResultados.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTBusca)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        fachada = FachadaSistema.getInstance();
        String busca = jTBusca.getText();
//        TableModel model = new TableModel.ge
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTBusca;
    private javax.swing.JTable jTResultados;
    // End of variables declaration//GEN-END:variables
}
