/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo.gui.myframes;

import java.sql.SQLException;
import java.time.Clock;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

import poo.dados.DAO.DisciplinaDAO;
import poo.excecoes.DiaNaoSelecionadoException;
import poo.excecoes.HorarioInvalidoException;
import poo.excecoes.HorarioInvalidoTMQIException;
import poo.excecoes.MinutosInvalidosException;
import poo.negocios.CadastroDisciplina;
import poo.negocios.FachadaSistema;
import poo.negocios.ListarDisciplinas;
import poo.negocios.beans.Aula;
import poo.negocios.beans.Curso;
import poo.negocios.beans.Disciplina;
/**
 *
 * @author Thiago Gomes
 */
public class FrameCadastroDisciplina extends javax.swing.JInternalFrame {
	private FachadaSistema auto;
	private String[] lista;
	private DefaultListModel model;
        
        ComboBoxModel<String> model3;
    /**
     * Creates new form FrameCadastrarDisciplina
     * @throws SQLException 
     */
    public FrameCadastroDisciplina(){
//        model = new DefaultListModel();
        initComponents();
        jTtrilha.setEnabled(false);
        preencherNomesCursos();
    }
    
//    public void preencherModel(){
//    	auto = FachadaSistema.getInstance();
//    	lista = auto.listarCodigo();
//    	for(int i = 0; i < lista.length; i++){
//        	System.out.println(lista[i]);
//        	model.addElement(lista[i]);
//        }
//    }
    
    public void preencherNomesCursos(){
    	auto = FachadaSistema.getInstance();
    	ArrayList<String> aux = auto.listarCursosPorNomeList();
        System.out.println(aux.toString());
    	for(String a : aux){
            System.out.println(a);
    		jCNomeCurso.addItem(a);
    	}
    	
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws SQLException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tipoDisciplina = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTNomeArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jROptativa = new javax.swing.JRadioButton();
        jRObrigatoria = new javax.swing.JRadioButton();
        jTNomeDis = new javax.swing.JTextField();
        jTtrilha = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jCarga = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jCNomeCurso = new javax.swing.JComboBox<>();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();

        jLabel1.setText("jLabel1");

        tipoDisciplina.add(jRObrigatoria);
        tipoDisciplina.add(jROptativa);

        setClosable(true);
        setTitle("Cadastro Disciplina");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da disciplina"));

        jLabel10.setText("Tipo:*");

        jLabel5.setText("Trilha:");

        jLabel2.setText("Nome:*");

        jLabel4.setText("Area:*");

        jLabel3.setText("Curso:*");

        jROptativa.setText("Optativa");
        jROptativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jROptativaActionPerformed(evt);
            }
        });

        jRObrigatoria.setText("Obrigatoria");
        jRObrigatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRObrigatoriaActionPerformed(evt);
            }
        });

        jTNomeDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeDisActionPerformed(evt);
            }
        });

        jTtrilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtrilhaActionPerformed(evt);
            }
        });

        jLabel11.setText("Carga Horaria:*");

        jCarga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30", "60", "120", "240" }));

        jLabel13.setText("(*) Campos obrigatorios");

        jCNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCNomeCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNomeDis)
                            .addComponent(jTNomeArea)
                            .addComponent(jCNomeCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jRObrigatoria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jROptativa))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(jTtrilha))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTNomeDis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTNomeArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jRObrigatoria)
                        .addComponent(jROptativa))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTtrilha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jToggleButton6.setText("Adicionar");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToggleButton7.setText("Limpar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jToggleButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton6)
                    .addComponent(jToggleButton7))
                .addContainerGap(223, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTNomeDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomeDisActionPerformed

    private void jTtrilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtrilhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtrilhaActionPerformed

    private void jRObrigatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRObrigatoriaActionPerformed
        // TODO add your handling code here:
        if(jRObrigatoria.isSelected()){
            jTtrilha.setEnabled(false);
        }
    }//GEN-LAST:event_jRObrigatoriaActionPerformed

    private void jROptativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jROptativaActionPerformed
        // TODO add your handling code here:
        if(jROptativa.isSelected()){
            jTtrilha.setEnabled(true);
            jTtrilha.setText("");
        }
    }//GEN-LAST:event_jROptativaActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        FachadaSistema comand = FachadaSistema.getInstance();
        try{
            Curso curso1 = new Curso(1, "Bacharelado em ciencia da computação");
            String nome = jTNomeDis.getText();
            String curso = jCNomeCurso.getSelectedItem().toString();
            String area = jTNomeArea.getText();
            String trilha = jTtrilha.getText();
            boolean obg = jRObrigatoria.isSelected();
            boolean opt = jROptativa.isSelected();
            Object carga = jCarga.getSelectedItem();
            String cargaFinal = carga.toString();
            int valor = Integer.parseInt(cargaFinal);
            int aux1 = 0 , aux2;
            if(obg){
                aux1 = 0;
            }else{
                aux1 = 1;
            }
        }catch(Exception e){
            
        }
        
        
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jCNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCNomeCursoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCNomeCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jCNomeCurso;
    private javax.swing.JComboBox<String> jCarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRObrigatoria;
    private javax.swing.JRadioButton jROptativa;
    private javax.swing.JTextField jTNomeArea;
    private javax.swing.JTextField jTNomeDis;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JTextField jTtrilha;
    private javax.swing.ButtonGroup tipoDisciplina;
    // End of variables declaration//GEN-END:variables
}
